### 1. 정상 요청
POST http://localhost:8080/payment
Content-Type: application/json

{
  "amount": 50000,
  "orderId": "MY-ORDER-001"
}

### 2. 진상 요청
POST http://localhost:8080/payment
Content-Type: application/json

{
  "amount": -50000,
  "orderId": "BAD-ORDER"
}